import { NextResponse } from 'next/server';
import { askGemini } from '../../../lib/gemini';
const fallback=[
 {topic:'Scanning',difficulty:5,question:'You receive between the lines with pressure arriving from behind. What should happen before the ball reaches you?',options:['Scan early, check the defender and choose the next action before the touch','Only look at the ball until your first touch','Turn immediately every time','Wait for a teammate to shout'],correct_index:0,explanation:'Elite receiving starts before the ball arrives. Information from scanning changes your body orientation and first action.'},
 {topic:'Pressing triggers',difficulty:5,question:'Your opponent receives facing their own goal near the sideline. What makes this a strong pressing moment?',options:['The receiver has limited forward options and the sideline can act as an extra defender','The opponent is always easy to tackle there','Your team should sprint regardless of cover','The ball is near the halfway line'],correct_index:0,explanation:'Good pressing is coordinated around triggers and cover, not just running toward the ball.'},
 {topic:'Rest defence',difficulty:5,question:'Your team attacks with many players. What is the main purpose of rest defence?',options:['Protect against the opponent transition if possession is lost','Keep every defender inside the penalty area','Stop all forward passes','Slow your own attack'],correct_index:0,explanation:'Rest defence preserves protection behind the ball so attacking numbers do not create an easy counterattack.'},
 {topic:'Third-man play',difficulty:4,question:'A midfielder is tightly marked and cannot receive cleanly. What can a third-man combination create?',options:['A way to use a teammate as a bounce option and move the ball into the next space','A reason to stop the attack','A guaranteed 1v1','A reason to play backwards forever'],correct_index:0,explanation:'Third-man actions manipulate the opponent by separating the receiver from the final passing lane.'},
 {topic:'Transitions',difficulty:5,question:'Your team wins the ball immediately after losing it. What is the first tactical question?',options:['Can we exploit the opponent before they regain defensive structure?','Who should waste the most time?','Should everyone run toward the ball?','Should we always shoot?'],correct_index:0,explanation:'The first seconds after a turnover can expose disorganized opponents. The decision depends on space, support and risk.'},
 {topic:'Body orientation',difficulty:4,question:'Why can an open body shape be valuable when receiving under pressure?',options:['It can let you see more of the field and play forward faster','It guarantees you will never lose the ball','It makes every pass stronger','It removes the need to scan'],correct_index:0,explanation:'Body orientation affects what information and actions are available after the first touch.'},
 {topic:'Tempo',difficulty:5,question:'When should a team change tempo rather than simply play faster?',options:['When a sudden change can disorganize the opponent or exploit a new space','Whenever the team is tired','Only after halftime','Only when losing'],correct_index:0,explanation:'Tempo is a tactical tool. Changing speed at the right moment can manipulate defensive organization.'},
 {topic:'Space',difficulty:5,question:'A teammate attracts two defenders in one zone. What should you look for next?',options:['The space created elsewhere and the player who can exploit it','Another teammate entering the same crowded zone','A guaranteed long shot','Stopping movement'],correct_index:0,explanation:'Overloads are valuable because they can create free players or space elsewhere, not because crowding itself is the goal.'}
];
export async function POST(request){const {profile,language='en',unit='scanning & space'}=await request.json().catch(()=>({}));const prompt=`You are Pitchpath's elite football-IQ coach. Create 8 hard but teachable match-decision questions for a teenage player. This is gamified learning, not trivia. PLAYER: ${JSON.stringify(profile||{})} LANGUAGE: ${language==='sv'?'Swedish':'English'} LESSON: ${unit} Make situations position-relevant, realistic and professional-level: scanning, body orientation, pressing triggers, third-player actions, rest defence, transitions, manipulating opponents, receiving under pressure, tempo and space. Avoid generic rules questions. Difficulty 4-5/5. Every question must have one best answer and a short explanation teaching the principle. Return ONLY compact JSON array of objects with topic,difficulty,question,options,correct_index,explanation.`;try{const text=await askGemini(prompt);const parsed=JSON.parse(text.replace(/```json|```/g,'').trim());if(!Array.isArray(parsed)||parsed.length<4)throw new Error('Invalid theory payload');return NextResponse.json({questions:parsed.slice(0,8)})}catch{return NextResponse.json({questions:fallback})}}
