'use client';
import { useEffect, useMemo, useState } from 'react';
import { supabase } from '../../lib/supabaseClient';

export default function NutritionPage() {
  const [userId,setUserId]=useState(null); const [profile,setProfile]=useState(null); const [logs,setLogs]=useState([]); const [plan,setPlan]=useState(null); const [loading,setLoading]=useState(true); const [planning,setPlanning]=useState(false); const [mealType,setMealType]=useState('breakfast'); const [description,setDescription]=useState(''); const [scanResult,setScanResult]=useState(null); const [scanning,setScanning]=useState(false);
  const today=new Date().toISOString().slice(0,10);
  const totals=useMemo(()=>logs.reduce((a,l)=>({cal:a.cal+(l.estimated_calories||0),protein:a.protein+(l.estimated_protein_g||0),carbs:a.carbs+(l.estimated_carbs_g||0),fat:a.fat+(l.estimated_fat_g||0)}),{cal:0,protein:0,carbs:0,fat:0}),[logs]);
  async function load(uid){const [{data:l},{data:p},{data:events},{data:injuries},{data:existing}]=await Promise.all([supabase.from('nutrition_logs').select('*').eq('user_id',uid).eq('date',today).order('created_at'),supabase.from('profiles').select('*').eq('id',uid).single(),supabase.from('calendar_events').select('*').eq('user_id',uid).gte('starts_at',new Date().toISOString()).order('starts_at').limit(8),supabase.from('injuries').select('*').eq('user_id',uid).eq('status','active'),supabase.from('nutrition_plans').select('*').eq('user_id',uid).eq('plan_date',today).maybeSingle()]);setLogs(l||[]);setProfile(p);if(existing)setPlan(existing)}
  useEffect(()=>{supabase.auth.getUser().then(({data})=>{if(data.user){setUserId(data.user.id);load(data.user.id)}setLoading(false)})},[]);
  async function generatePlan(){setPlanning(true);const {data:events}=await supabase.from('calendar_events').select('*').eq('user_id',userId).gte('starts_at',new Date().toISOString()).order('starts_at').limit(10);const {data:injuries}=await supabase.from('injuries').select('*').eq('user_id',userId).eq('status','active');const res=await fetch('/api/nutrition-plan',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({profile,events,injuries,recentLogs:logs})});const out=await res.json();if(out.plan){const row={user_id:userId,plan_date:today,calories:out.plan.calories,protein_g:out.plan.protein_g,carbs_g:out.plan.carbs_g,fat_g:out.plan.fat_g,meals:out.plan.meals,rationale:out.plan.rationale};const {data:saved}=await supabase.from('nutrition_plans').upsert(row,{onConflict:'user_id,plan_date'}).select().single();setPlan(saved||row)}setPlanning(false)}
  async function addManual(){if(!description)return;await supabase.from('nutrition_logs').insert({user_id:userId,meal_type:mealType,food_description:description,confirmed:true});setDescription('');load(userId)}
  function fileToBase64(file){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result.split(',')[1]);r.onerror=reject;r.readAsDataURL(file)})}
  async function handlePhoto(e){const file=e.target.files?.[0];if(!file)return;setScanning(true);setScanResult(null);try{const base64Image=await fileToBase64(file);const res=await fetch('/api/scan-food',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({base64Image,mimeType:file.type})});setScanResult(await res.json())}finally{setScanning(false)}}
  async function confirmScan(){if(!scanResult||scanResult.error)return;await supabase.from('nutrition_logs').insert({user_id:userId,meal_type:mealType,food_description:scanResult.food_name,estimated_calories:scanResult.estimated_calories,estimated_protein_g:scanResult.estimated_protein_g,estimated_carbs_g:scanResult.estimated_carbs_g,estimated_fat_g:scanResult.estimated_fat_g,confidence:scanResult.confidence,confirmed:true});setScanResult(null);load(userId)}
  if(loading)return <main className="app-shell"><div className="card">Loading nutrition system…</div></main>;
  return <main className="app-shell"><div style={{marginBottom:22}}><span className="pill">Performance nutrition</span><h1 className="page-title" style={{marginTop:10}}>Fuel the player.</h1><p className="page-subtitle">A daily plan that changes with school, football, recovery and what you actually eat.</p></div>
    <section className="card" style={{background:'linear-gradient(135deg,#202522,#39433D)',color:'#fff'}}><div style={{display:'flex',justifyContent:'space-between',gap:18,alignItems:'center',flexWrap:'wrap'}}><div><div style={{fontSize:12,opacity:.65,fontWeight:800,letterSpacing:'.08em'}}>TODAY</div><h2 style={{fontSize:32,marginTop:6}}>Your fueling plan</h2><p style={{opacity:.75,maxWidth:620,marginBottom:0}}>{plan?.rationale||'Generate a plan built around your actual day. Regular meals and enough energy come first.'}</p></div><button className="btn-secondary" style={{background:'rgba(255,255,255,.1)',color:'#fff',borderColor:'rgba(255,255,255,.18)'}} onClick={generatePlan} disabled={planning}>{planning?'Building…':'Build today’s plan'}</button></div></section>
    {plan&&<section className="premium-grid"><div className="premium-tile"><span className="pill">Energy</span><div className="metric">{plan.calories||'—'}</div><div className="muted">kcal target</div></div><div className="premium-tile"><span className="pill">Protein</span><div className="metric">{plan.protein_g||'—'}g</div><div className="muted">daily target</div></div><div className="premium-tile"><span className="pill">Carbs</span><div className="metric">{plan.carbs_g||'—'}g</div><div className="muted">daily target</div></div><div className="premium-tile"><span className="pill">Fat</span><div className="metric">{plan.fat_g||'—'}g</div><div className="muted">daily target</div></div></section>}
    <section className="card"><div style={{display:'flex',justifyContent:'space-between',alignItems:'end',gap:12}}><div><span className="pill">Logged</span><h2 style={{fontSize:27,marginTop:9}}>Today so far</h2></div><div style={{textAlign:'right'}}><strong>{totals.cal}</strong> kcal<br/><span className="muted">{totals.protein}g protein</span></div></div><div className="premium-grid" style={{marginTop:16}}><div className="premium-tile"><strong>{totals.carbs}g</strong><div className="muted">carbs</div></div><div className="premium-tile"><strong>{totals.fat}g</strong><div className="muted">fat</div></div></div>{logs.length===0&&<p className="muted">Nothing logged yet. Your plan will adapt tomorrow based on what you actually managed to eat.</p>}{logs.map(l=><div key={l.id} className="soft-divider" style={{paddingTop:12}}><strong>{l.meal_type}</strong> · {l.food_description}<span className="muted"> {l.estimated_calories?`· ${l.estimated_calories} kcal`:''}</span></div>)}</section>
    {plan?.meals?.length>0&&<section className="card"><span className="pill">Meal plan</span><h2 style={{fontSize:27,marginTop:9}}>What to eat today</h2>{plan.meals.map((m,i)=><div key={i} className="premium-tile" style={{marginTop:12}}><div style={{display:'flex',justifyContent:'space-between',gap:12}}><strong>{m.title}</strong><span className="muted">{m.time}</span></div><div className="muted" style={{marginTop:7}}>{(m.foods||[]).join(' · ')}</div><small className="muted">{m.purpose}</small></div>)}</section>}
    <section className="card"><span className="pill">Log food</span><h2 style={{fontSize:27,marginTop:9}}>Add what you ate</h2><select className="input-field" value={mealType} onChange={e=>setMealType(e.target.value)} style={{marginTop:14}}><option>breakfast</option><option>lunch</option><option>dinner</option><option>snack</option></select><div style={{display:'flex',gap:9,marginTop:10}}><input className="input-field" placeholder="e.g. chicken pasta" value={description} onChange={e=>setDescription(e.target.value)}/><button className="btn-primary" onClick={addManual}>Add</button></div><div style={{marginTop:18}}><label className="btn-secondary" style={{display:'inline-block',cursor:'pointer'}}>Take food photo<input type="file" accept="image/*" capture="environment" onChange={handlePhoto} style={{display:'none'}}/></label></div>{scanning&&<p className="muted">Analyzing photo…</p>}{scanResult&&!scanResult.error&&<div className="premium-tile" style={{marginTop:14}}><strong>{scanResult.food_name}</strong><p className="muted">~{scanResult.estimated_calories} kcal · {scanResult.estimated_protein_g}g protein · {scanResult.estimated_carbs_g}g carbs · {scanResult.estimated_fat_g}g fat</p><button className="btn-primary" onClick={confirmScan}>Confirm & log</button></div>}{scanResult?.error&&<p style={{color:'var(--danger)'}}>{scanResult.error}</p>}</section>
  </main>
}
