'use client';
import { useEffect,useState } from 'react';
import { supabase } from '../../lib/supabaseClient';
export default function TheoryPage(){const [uid,setUid]=useState(null),[profile,setProfile]=useState(null),[questions,setQuestions]=useState([]),[current,setCurrent]=useState(0),[selected,setSelected]=useState(null),[streak,setStreak]=useState(0),[loading,setLoading]=useState(false);
 useEffect(()=>{(async()=>{const {data:u}=await supabase.auth.getUser();if(!u.user)return;setUid(u.user.id);const {data:p}=await supabase.from('profiles').select('*').eq('id',u.user.id).single();setProfile(p);const {data}=await supabase.from('theory_questions').select('*').order('difficulty',{ascending:false}).limit(5);if(data?.length)setQuestions(data)})()},[]);
 async function generateMore(){setLoading(true);const res=await fetch('/api/generate-theory-questions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({profile})});const out=await res.json();if(out.questions?.length){const {data}=await supabase.from('theory_questions').insert(out.questions).select();setQuestions(data||out.questions);setCurrent(0)}setLoading(false)}
 async function answer(i){setSelected(i);const correct=i===questions[current].correct_index;if(correct)setStreak(s=>s+1);else setStreak(0);await supabase.from('theory_progress').insert({user_id:uid,question_id:questions[current].id,answered_correctly:correct})}
 const q=questions[current];if(!q)return <main className="app-shell"><section className="card"><span className="pill">Football IQ</span><h1 className="page-title" style={{marginTop:10}}>Train the mind.</h1><p className="page-subtitle">Scenario-based tactical problems built for serious players.</p><button className="btn-primary" style={{marginTop:18}} onClick={generateMore} disabled={loading}>{loading?'Building lesson…':'Start advanced lesson'}</button></section></main>;
 return <main className="app-shell"><div style={{marginBottom:22}}><span className="pill">Football IQ · Level {q.difficulty}/5</span><h1 className="page-title" style={{marginTop:10}}>See the pitch earlier.</h1><p className="page-subtitle">Hard situations. Better scanning. Better decisions.</p></div><section className="card"><div style={{display:'flex',justifyContent:'space-between',gap:12}}><span className="pill">{q.topic}</span><strong>🔥 {streak}</strong></div><h2 style={{fontSize:28,lineHeight:1.15,marginTop:20}}>{q.question}</h2><div style={{marginTop:20}}>{q.options.map((opt,i)=><button key={i} onClick={()=>selected===null&&answer(i)} className="premium-tile" style={{display:'block',width:'100%',textAlign:'left',marginBottom:9,border:i===q.correct_index&&selected!==null?'2px solid var(--pine)':'1px solid rgba(255,255,255,.7)',background:selected===null?'rgba(255,252,249,.62)':i===q.correct_index?'rgba(131,151,136,.2)':i===selected?'rgba(142,85,77,.16)':'rgba(255,252,249,.5)'}}><strong>{String.fromCharCode(65+i)}</strong> <span style={{marginLeft:8}}>{opt}</span></button>)}</div>{selected!==null&&<div className="premium-tile" style={{marginTop:14}}><span className="pill">Why</span><p style={{marginBottom:0}}>{q.explanation}</p><button className="btn-primary" style={{marginTop:10}} onClick={()=>{setSelected(null);if(current+1<questions.length)setCurrent(current+1);else generateMore()}}>Next</button></div>}</section></main>}
