'use client';
import { useEffect,useState } from 'react';
import { supabase } from '../../lib/supabaseClient';

const units=[
 {title:'Scan before you receive',sub:'See the next action before the ball arrives.',icon:'◉'},
 {title:'Create & attack space',sub:'Manipulate defenders instead of chasing the ball.',icon:'◌'},
 {title:'Pressing triggers',sub:'Recognise the moment the team should jump.',icon:'↗'},
 {title:'Transitions',sub:'Turn the first two seconds into an advantage.',icon:'⇄'},
 {title:'Rest defence',sub:'Protect the team while attacking.',icon:'◇'},
 {title:'Game control',sub:'Use tempo, positioning and information.',icon:'✦'}
];
const sv={en:{iq:'Football IQ',title:'Think one move ahead.',sub:'A progressive football-IQ path built around difficult match decisions.',streak:'streak',xp:'XP',hearts:'lives',start:'Start lesson',continue:'Continue',complete:'Lesson complete',next:'Next decision',finish:'Finish lesson',correct:'Correct',wrong:'Not quite',loading:'Building your lesson…',coach:'Coach note'},sv:{iq:'Fotbolls-IQ',title:'Tänk ett steg före.',sub:'En progressiv väg byggd kring svåra matchsituationer.',streak:'streak',xp:'XP',hearts:'liv',start:'Starta lektion',continue:'Fortsätt',complete:'Lektion klar',next:'Nästa beslut',finish:'Avsluta lektion',correct:'Rätt',wrong:'Inte riktigt',loading:'Bygger din lektion…',coach:'Tränarens tanke'}};

export default function TheoryPage(){
 const [uid,setUid]=useState(null),[profile,setProfile]=useState(null),[language,setLanguage]=useState('en'),[unit,setUnit]=useState(0),[questions,setQuestions]=useState([]),[current,setCurrent]=useState(0),[selected,setSelected]=useState(null),[xp,setXp]=useState(0),[streak,setStreak]=useState(0),[hearts,setHearts]=useState(5),[loading,setLoading]=useState(false),[done,setDone]=useState(false);
 const t=sv[language]||sv.en;
 useEffect(()=>{(async()=>{const {data}=await supabase.auth.getUser();if(!data.user)return;setUid(data.user.id);const {data:p}=await supabase.from('profiles').select('*').eq('id',data.user.id).single();setProfile(p);setLanguage(p?.language||localStorage.getItem('pitchpath-language')||'en')})()},[]);
 async function startLesson(index=unit){setLoading(true);setDone(false);setSelected(null);setCurrent(0);setHearts(5);const res=await fetch('/api/generate-theory-questions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({profile,language,unit:units[index].title})});const out=await res.json();setQuestions(out.questions||[]);setLoading(false)}
 async function answer(index){if(selected!==null)return;setSelected(index);const q=questions[current];const correct=index===q.correct_index;if(correct){setXp(x=>x+10);setStreak(s=>s+1)}else{setHearts(h=>Math.max(0,h-1));setStreak(0)}if(uid&&q.id)await supabase.from('theory_progress').insert({user_id:uid,question_id:q.id,answered_correctly:correct});}
 function next(){if(current+1>=questions.length){setDone(true);return}setSelected(null);setCurrent(c=>c+1)}
 if(loading)return <main className="app-shell" style={{maxWidth:760}}><div className="card theory-loading"><div className="theory-orbit">✦</div><h2>{t.loading}</h2><p className="muted">Pitchpath is adapting the lesson to your position and level.</p></div></main>;
 if(!questions.length&&!done)return <main className="app-shell theory-shell"><div className="theory-header"><div><span className="pill">{t.iq}</span><h1 className="page-title" style={{marginTop:10}}>{t.title}</h1><p className="page-subtitle">{t.sub}</p></div><div className="theory-stats"><div>🔥<b>{streak}</b><small>{t.streak}</small></div><div>⚡<b>{xp}</b><small>{t.xp}</small></div><div>♥<b>{hearts}</b><small>{t.hearts}</small></div></div></div><section className="theory-path"><div className="theory-path-line"/>{units.map((u,i)=><button key={u.title} className={`theory-unit ${i===unit?'selected':''} ${i<unit?'done':''}`} onClick={()=>setUnit(i)}><span className="theory-node">{u.icon}</span><span><b>{u.title}</b><small>{u.sub}</small></span>{i<unit&&<em>✓</em>}</button>)}</section><button className="btn-primary theory-start" onClick={()=>startLesson(unit)}>{unit?'Continue':'Start lesson'} →</button></main>;
 if(done)return <main className="app-shell" style={{maxWidth:650}}><div className="card theory-complete"><div className="complete-mark">✓</div><span className="pill">{t.iq}</span><h1 style={{fontSize:42,marginTop:10}}>{t.complete}</h1><p className="muted">+{xp} XP · {streak} {t.streak} · {Math.max(0,hearts)} {t.hearts}</p><button className="btn-primary" style={{marginTop:18}} onClick={()=>startLesson(unit)}>{t.continue} →</button></div></main>;
 const q=questions[current];const correct=selected!==null&&selected===q.correct_index;return <main className="app-shell" style={{maxWidth:700}}><div className="lesson-top"><button className="lesson-close" onClick={()=>setQuestions([])}>×</button><div className="lesson-progress"><div style={{width:`${((current)/questions.length)*100}%`}}/></div><span>♥ {hearts}</span></div><section className="lesson-card"><div className="lesson-meta"><span>{q.topic}</span><span>{q.difficulty}/5</span></div><p className="lesson-question">{q.question}</p><div className="lesson-options">{q.options?.map((opt,i)=><button key={i} disabled={selected!==null} className={selected===null?'':i===q.correct_index?'answer-correct':i===selected?'answer-wrong':''} onClick={()=>answer(i)}><span>{String.fromCharCode(65+i)}</span>{opt}</button>)}</div>{selected!==null&&<div className={`answer-note ${correct?'good':'bad'}`}><b>{correct?t.correct:t.wrong}</b><p>{q.explanation}</p><small>{t.coach}: apply the principle to the next situation, not just this question.</small></div>}{selected!==null&&<button className="btn-primary" style={{width:'100%',marginTop:16}} onClick={next}>{current+1<questions.length?t.next:t.finish} →</button>}</section></main>
}
