'use client';
import { useEffect,useState } from 'react';
import { supabase } from '../../lib/supabaseClient';
export default function TheoryPage(){const [userId,setUserId]=useState(null),[profile,setProfile]=useState(null),[questions,setQuestions]=useState([]),[current,setCurrent]=useState(0),[selected,setSelected]=useState(null),[streak,setStreak]=useState(0),[loading,setLoading]=useState(false);
useEffect(()=>{(async()=>{const {data}=await supabase.auth.getUser();if(!data.user)return;setUserId(data.user.id);const {data:p}=await supabase.from('profiles').select('*').eq('id',data.user.id).single();setProfile(p);await loadQuestions()})()},[]);
async function loadQuestions(){const {data}=await supabase.from('theory_questions').select('*').limit(4);if(data?.length)setQuestions(data)}
async function generateMore(){setLoading(true);try{const res=await fetch('/api/generate-theory-questions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({profile})});const {questions:newQs}=await res.json();if(newQs?.length){const {data:inserted}=await supabase.from('theory_questions').insert(newQs).select();setQuestions(inserted||newQs);setCurrent(0)}}finally{setLoading(false)}}
async function answer(index){setSelected(index);const correct=index===questions[current].correct_index;if(correct)setStreak(s=>s+1);else setStreak(0);await supabase.from('theory_progress').insert({user_id:userId,question_id:questions[current].id,answered_correctly:correct});if(current===questions.length-2)generateMore()}
function next(){setSelected(null);if(current+1<questions.length)setCurrent(current+1);else generateMore()}
if(questions.length===0)return <main className="app-shell" style={{maxWidth:620}}><div className="card"><span className="pill">Football IQ</span><h2 style={{fontSize:30,marginTop:10}}>Train how you think.</h2><p className="muted">Pitchpath generates difficult, position-aware match decisions instead of basic football trivia.</p><button className="btn-primary" onClick={generateMore} disabled={loading}>{loading?'Preparing…':'Start lesson'}</button></div></main>;
const q=questions[current];return <main className="app-shell" style={{maxWidth:620}}><div className="card"><div style={{display:'flex',justifyContent:'space-between',marginBottom:14}}><span className="pill">{q.topic} · {q.difficulty}/5</span><span style={{fontSize:13}}>🔥 {streak}</span></div><div className="progress-track" style={{marginBottom:18}}><div className="progress-fill" style={{width:`${((current+1)/questions.length)*100}%`}}/></div><p style={{fontSize:20,fontWeight:700,lineHeight:1.35}}>{q.question}</p>{q.options.map((opt,i)=><button key={i} onClick={()=>selected===null&&answer(i)} style={{display:'block',width:'100%',textAlign:'left',padding:'15px 16px',marginBottom:9,borderRadius:18,border:'1.5px solid var(--stone)',background:selected===null?'var(--card)':i===q.correct_index?'var(--sage)':i===selected?'#e8b3ae':'var(--card)',color:selected!==null&&i===q.correct_index?'#fff':'var(--ink)',transition:'all .22s ease'}}>{opt}</button>)}{selected!==null&&<><p className="muted" style={{marginTop:12}}>{q.explanation}</p><button className="btn-primary" style={{marginTop:10}} onClick={next}>{current+1<questions.length?'Next decision':'Build next set'}</button></>}</div></main>}
