import { useState } from 'react';
import { ActivityIndicator, Alert, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { useQuery } from '@tanstack/react-query';
import { supabase } from '@/lib/supabase';
import { colors, radius } from '@/lib/theme';
import { askPitchpath } from '@/services/ai';
import { getProfile } from '@/services/profile';

export default function AI(){
 const [input,setInput]=useState(''); const [messages,setMessages]=useState<Array<{role:string,text:string}>>([]); const [busy,setBusy]=useState(false);
 const {data:user}=useQuery({queryKey:['user'],queryFn:async()=> (await supabase.auth.getUser()).data.user});
 const {data:profile}=useQuery({queryKey:['profile',user?.id],enabled:!!user,queryFn:()=>getProfile(user!.id)});
 const send=async()=>{const message=input.trim();if(!message||!user)return;setInput('');setMessages(m=>[...m,{role:'you',text:message}]);setBusy(true);try{const result=await askPitchpath({userId:user.id,message,context:{profile}});setMessages(m=>[...m,{role:'pitchpath',text:result.message}]);}catch(e){Alert.alert('AI unavailable',e instanceof Error?e.message:String(e));}finally{setBusy(false);}};
 return <View style={s.screen}><ScrollView contentContainerStyle={s.page} contentInsetAdjustmentBehavior="automatic"><Text style={s.eyebrow}>INTELLIGENCE</Text><Text style={s.title}>Pitchpath AI</Text><Text style={s.sub}>Ask naturally. Calendar changes should be verified before Pitchpath says they are done.</Text>{messages.length===0&&<View style={s.example}><Text style={s.exampleTitle}>Try</Text><Text style={s.exampleText}>“I want gym every Monday.”{`\n`}“Add study Monday 18 to 19.”{`\n`}“Make this week lighter.”</Text></View>}{messages.map((m,i)=><View key={i} style={[s.message,m.role==='you'?s.you:s.ai]}><Text style={[s.messageText,m.role==='you'&&{color:colors.white}]}>{m.text}</Text></View>)}{busy&&<View style={s.loading}><ActivityIndicator color={colors.deepSage}/><Text style={s.loadingText}>Checking your context…</Text></View>}</ScrollView><View style={s.composer}><TextInput value={input} onChangeText={setInput} placeholder="Tell Pitchpath what you need…" placeholderTextColor={colors.muted} style={s.input} multiline/><Pressable onPress={send} disabled={busy} style={s.send}><Text style={s.sendText}>↑</Text></Pressable></View></View>;
}
const s=StyleSheet.create({screen:{flex:1,backgroundColor:colors.surface},page:{padding:22,paddingBottom:130,gap:10},eyebrow:{fontSize:11,letterSpacing:1.8,color:colors.deepSage,fontWeight:'800'},title:{fontSize:34,color:colors.ink,fontWeight:'700'},sub:{fontSize:15,lineHeight:22,color:colors.muted,marginBottom:8},example:{padding:18,borderRadius:radius.lg,backgroundColor:colors.sand},exampleTitle:{fontSize:13,color:colors.deepSage,fontWeight:'800'},exampleText:{fontSize:15,lineHeight:25,color:colors.ink,marginTop:5},message:{maxWidth:'90%',padding:15,borderRadius:18},you:{alignSelf:'flex-end',backgroundColor:colors.ink,borderBottomRightRadius:5},ai:{alignSelf:'flex-start',backgroundColor:colors.white,borderWidth:1,borderColor:colors.blush,borderBottomLeftRadius:5},messageText:{fontSize:15,lineHeight:21,color:colors.ink},loading:{flexDirection:'row',alignItems:'center',gap:8,padding:8},loadingText:{fontSize:12,color:colors.muted},composer:{position:'absolute',bottom:0,left:0,right:0,padding:12,paddingBottom:24,backgroundColor:colors.surface,borderTopWidth:1,borderTopColor:colors.blush,flexDirection:'row',gap:8},input:{flex:1,minHeight:48,maxHeight:110,borderRadius:24,backgroundColor:colors.white,borderWidth:1,borderColor:colors.blush,paddingHorizontal:17,paddingVertical:12,color:colors.ink},send:{width:48,height:48,borderRadius:24,backgroundColor:colors.deepSage,alignItems:'center',justifyContent:'center'},sendText:{color:colors.white,fontSize:23,fontWeight:'700'}});
