import { useState } from 'react';
import { Alert, Image, Pressable, ScrollView, StyleSheet, Switch, Text, View } from 'react-native';
import * as ImagePicker from 'expo-image-picker';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { supabase } from '@/lib/supabase';
import { colors, radius } from '@/lib/theme';
import { getProfile, uploadProfilePhoto } from '@/services/profile';

export default function More(){
 const qc=useQueryClient(); const [dark,setDark]=useState(false); const {data:user}=useQuery({queryKey:['user'],queryFn:async()=> (await supabase.auth.getUser()).data.user}); const {data:profile}=useQuery({queryKey:['profile',user?.id],enabled:!!user,queryFn:()=>getProfile(user!.id)});
 const pick=async(camera=false)=>{const permission=camera?await ImagePicker.requestCameraPermissionsAsync():await ImagePicker.requestMediaLibraryPermissionsAsync();if(!permission.granted)return Alert.alert('Permission needed','Allow photo access to continue.');const result=camera?await ImagePicker.launchCameraAsync({mediaTypes:['images'],quality:.85}):await ImagePicker.launchImageLibraryAsync({mediaTypes:['images'],quality:.85});if(!result.canceled&&user){try{await uploadProfilePhoto(user.id,result.assets[0].uri);await qc.invalidateQueries({queryKey:['profile',user.id]});}catch(e){Alert.alert('Upload failed',e instanceof Error?e.message:String(e));}}};
 return <ScrollView contentInsetAdjustmentBehavior="automatic" contentContainerStyle={s.page}><Text style={s.eyebrow}>PLAYER</Text><Text style={s.title}>More</Text><View style={s.profile}>{profile?.photo_url?<Image source={{uri:profile.photo_url}} style={s.avatar}/>:<View style={s.avatar}><Text style={s.avatarText}>{profile?.name?.[0]??'P'}</Text></View>}<View style={{flex:1}}><Text style={s.name}>{profile?.name??'Your profile'}</Text><Text style={s.meta}>{profile?.position??'Position not set'}{profile?.team?` · ${profile.team}`:''}</Text></View></View><Text style={s.section}>Profile photo</Text><View style={s.row}><Pressable onPress={()=>pick(false)} style={s.secondary}><Text style={s.secondaryText}>Choose photo</Text></Pressable><Pressable onPress={()=>pick(true)} style={s.secondary}><Text style={s.secondaryText}>Take photo</Text></Pressable></View><Text style={s.section}>Preferences</Text><View style={s.setting}><View><Text style={s.settingTitle}>Dark mode</Text><Text style={s.settingText}>Prepared for intentional light and dark themes.</Text></View><Switch value={dark} onValueChange={setDark} /></View><View style={s.setting}><View><Text style={s.settingTitle}>Language</Text><Text style={s.settingText}>{profile?.language==='sv'?'Svenska':'English'}</Text></View><Text style={s.chevron}>›</Text></View><Pressable onPress={async()=>{const {error}=await supabase.auth.signOut();if(error)Alert.alert('Could not log out',error.message)}} style={s.logout}><Text style={s.logoutText}>Log out</Text></Pressable></ScrollView>;
}
const s=StyleSheet.create({page:{padding:22,gap:10,paddingBottom:110,backgroundColor:colors.surface},eyebrow:{fontSize:11,letterSpacing:1.8,color:colors.deepSage,fontWeight:'800'},title:{fontSize:34,color:colors.ink,fontWeight:'700'},profile:{marginTop:10,padding:16,borderRadius:radius.lg,backgroundColor:colors.white,borderWidth:1,borderColor:colors.blush,flexDirection:'row',alignItems:'center',gap:13},avatar:{width:58,height:58,borderRadius:20,backgroundColor:colors.sand,alignItems:'center',justifyContent:'center'},avatarText:{fontSize:24,color:colors.ink,fontWeight:'700'},name:{fontSize:18,color:colors.ink,fontWeight:'700'},meta:{fontSize:13,color:colors.muted,marginTop:3},section:{fontSize:18,color:colors.ink,fontWeight:'700',marginTop:18},row:{flexDirection:'row',gap:9},secondary:{flex:1,height:48,borderRadius:radius.md,backgroundColor:colors.white,borderWidth:1,borderColor:colors.blush,alignItems:'center',justifyContent:'center'},secondaryText:{color:colors.ink,fontWeight:'700'},setting:{minHeight:72,padding:16,borderRadius:radius.md,backgroundColor:colors.white,borderWidth:1,borderColor:colors.blush,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},settingTitle:{fontSize:15,color:colors.ink,fontWeight:'700'},settingText:{fontSize:12,color:colors.muted,marginTop:3},chevron:{fontSize:26,color:colors.muted},logout:{height:52,borderRadius:radius.md,backgroundColor:colors.blush,alignItems:'center',justifyContent:'center',marginTop:20},logoutText:{color:colors.ink,fontWeight:'800'}});
