import { useQuery } from '@tanstack/react-query';
import { ScrollView, StyleSheet, Text, View } from 'react-native';
import { supabase } from '@/lib/supabase';
import { colors, radius } from '@/lib/theme';

export default function Training(){
 const {data:user}=useQuery({queryKey:['user'],queryFn:async()=> (await supabase.auth.getUser()).data.user});
 const {data: sessions=[]}=useQuery({queryKey:['training',user?.id],enabled:!!user,queryFn:async()=>{const {data,error}=await supabase.from('training_sessions').select('*').eq('user_id',user!.id).order('scheduled_for',{ascending:true}).limit(10);if(error)throw error;return data??[];}});
 return <ScrollView contentInsetAdjustmentBehavior="automatic" contentContainerStyle={s.page}><Text style={s.eyebrow}>DEVELOPMENT</Text><Text style={s.title}>Training</Text><Text style={s.sub}>Your individual work should complement the team schedule, not compete with it.</Text><View style={s.focus}><Text style={s.focusKicker}>CURRENT FOCUS</Text><Text style={s.focusTitle}>Technical quality under pressure</Text><Text style={s.focusText}>Use your weaknesses and recent completion history to shape the next sessions.</Text></View><Text style={s.section}>Upcoming</Text>{sessions.length===0?<View style={s.empty}><Text style={s.emptyTitle}>No sessions yet.</Text><Text style={s.emptyText}>Your connected training plan will appear here once sessions are created.</Text></View>:sessions.map((x:any)=><View style={s.card} key={x.id}><Text style={s.date}>{x.scheduled_for ?? 'Flexible'}</Text><Text style={s.cardTitle}>{x.type ?? 'Individual session'}</Text><Text style={s.cardText}>{x.notes ?? 'Personalized football development session.'}</Text></View>)}</ScrollView>;
}
const s=StyleSheet.create({page:{padding:22,gap:9,paddingBottom:110,backgroundColor:colors.surface},eyebrow:{fontSize:11,letterSpacing:1.8,color:colors.deepSage,fontWeight:'800'},title:{fontSize:34,color:colors.ink,fontWeight:'700'},sub:{fontSize:15,lineHeight:22,color:colors.muted,marginBottom:8},focus:{padding:20,borderRadius:radius.xl,backgroundColor:colors.ink,marginTop:8},focusKicker:{fontSize:10,letterSpacing:1.5,color:colors.blush,fontWeight:'800'},focusTitle:{fontSize:24,lineHeight:29,color:colors.white,fontWeight:'700',marginTop:8},focusText:{fontSize:13,lineHeight:20,color:'#C8D0CB',marginTop:7},section:{fontSize:19,color:colors.ink,fontWeight:'700',marginTop:17},empty:{padding:20,borderRadius:radius.lg,backgroundColor:colors.sand},emptyTitle:{fontSize:19,color:colors.ink,fontWeight:'700'},emptyText:{fontSize:14,lineHeight:21,color:colors.muted,marginTop:6},card:{padding:17,borderRadius:radius.md,backgroundColor:colors.white,borderWidth:1,borderColor:colors.blush},date:{fontSize:11,color:colors.deepSage,fontWeight:'800'},cardTitle:{fontSize:18,color:colors.ink,fontWeight:'700',marginTop:4},cardText:{fontSize:13,color:colors.muted,lineHeight:19,marginTop:4}});
