import { NextResponse } from 'next/server';
import { askGemini } from '../../../lib/gemini';
export async function POST(request){const {profile,events,injuries}=await request.json();const language=profile?.language==='sv'?'Swedish':'English';const prompt=`You are the strength-and-conditioning coach inside Pitchpath for a teenage football player balancing school and football. Write all natural-language fields in ${language}.
PLAYER: ${JSON.stringify(profile)}
UPCOMING SCHEDULE: ${JSON.stringify(events||[])}
ACTIVE RECOVERY LIMITS: ${JSON.stringify(injuries||[])}
Build ONE demanding but age-appropriate academy-style gym session that is clearly individualized rather than generic. Personalize exercise selection, order, volume, rest and emphasis to position, football schedule, school load, goals, weaknesses and recovery. The player should feel they trained, but never use maximal testing, unsafe loading, punishment, failure training, supplements or restrictive dieting. Use RPE/RIR guidance and protect match freshness.
OPTIONAL PHOTO COACHING CONTEXT: ${profile?.photo_training_context||'none'}. Use only safe exercise setup/coaching cues; never judge appearance, body size, weight, body fat or development.
Periodize hard/moderate/easier weeks around match density and school load. A lower-load recovery week can appear when appropriate. If running/conditioning is needed, keep it in the individual-training system.
Return ONLY JSON: {"summary":"2-3 sentences","session_minutes":45,"effort":"RPE 7/10","week_focus":"...","exercises":[{"name":"...","sets":3,"reps":"6-10","rest_seconds":90,"effort":"RPE 7","purpose":"...","coaching":"..."}]}. Provide 6-8 football-relevant exercises.`;try{const text=await askGemini(prompt);return NextResponse.json(JSON.parse(text.replace(/```json|```/g,'').trim()))}catch{return NextResponse.json({summary:'A controlled football-strength session focused on unilateral strength, posterior-chain capacity and trunk robustness.',session_minutes:45,effort:'RPE 7/10',week_focus:'Build strength without compromising football freshness.',exercises:[]})}}
