import { NextResponse } from 'next/server';
import { askGemini } from '../../../lib/gemini';

const fallback={summary:'A controlled football-strength session focused on unilateral strength, posterior-chain capacity and trunk control. Keep every set technically clean and stop if pain appears.',session_minutes:45,effort:'RPE 6-7/10',week_focus:'Build strength without compromising football freshness.',exercises:[
 {name:'Split squat',sets:3,reps:'6-8 / side',rest_seconds:75,effort:'RPE 6-7',purpose:'Unilateral lower-body strength',coaching:'Controlled descent, stable knee and smooth drive.'},
 {name:'Single-leg hip hinge',sets:3,reps:'8 / side',rest_seconds:60,effort:'RPE 6-7',purpose:'Posterior-chain control',coaching:'Keep hips square and move slowly.'},
 {name:'Push-up',sets:3,reps:'8-12',rest_seconds:60,effort:'RPE 6-7',purpose:'Upper-body strength',coaching:'Keep ribs controlled and use a comfortable range.'},
 {name:'Row',sets:3,reps:'8-12',rest_seconds:60,effort:'RPE 6-7',purpose:'Upper-back strength',coaching:'Pull smoothly without shrugging.'},
 {name:'Calf raise',sets:3,reps:'10-15',rest_seconds:45,effort:'RPE 6-7',purpose:'Lower-leg capacity',coaching:'Pause briefly at the top and control the lowering.'},
 {name:'Dead bug',sets:3,reps:'6-8 / side',rest_seconds:45,effort:'RPE 6',purpose:'Trunk control',coaching:'Keep the lower back comfortably controlled.'}
]};

export async function POST(request){try{const {profile,events,injuries}=await request.json();const language=profile?.language==='sv'?'Swedish':'English';const prompt=`You are the strength-and-conditioning coach inside Pitchpath for a teenage football player balancing school and football. Write all natural-language fields in ${language}. PLAYER: ${JSON.stringify(profile)} UPCOMING SCHEDULE: ${JSON.stringify(events||[])} ACTIVE RECOVERY LIMITS: ${JSON.stringify(injuries||[])} Build ONE demanding but age-appropriate academy-style gym session that is clearly individualized rather than generic. Personalize exercise selection, order, volume, rest and emphasis to position, football schedule, school load, goals, weaknesses and recovery. The player should feel trained, but never use maximal testing, unsafe loading, punishment, failure training, supplements or restrictive dieting. Use RPE guidance and protect match freshness. OPTIONAL PHOTO COACHING CONTEXT: ${profile?.photo_training_context||'none'}. Use only safe exercise setup/coaching cues; never judge appearance, body size, weight, body fat or development. Return ONLY JSON: {"summary":"2-3 sentences","session_minutes":45,"effort":"RPE 7/10","week_focus":"...","exercises":[{"name":"...","sets":3,"reps":"6-10","rest_seconds":90,"effort":"RPE 7","purpose":"...","coaching":"..."}]}. Provide 6-8 football-relevant exercises.`;const text=await askGemini(prompt);const parsed=JSON.parse(text.replace(/```json|```/g,'').trim());return NextResponse.json(parsed?.exercises?.length?parsed:fallback)}catch{return NextResponse.json(fallback)}}
