'use client';
import Link from 'next/link';
import { usePathname } from 'next/navigation';
import { useEffect,useState } from 'react';
const links=[
 {href:'/',en:'Overview',sv:'Översikt',icon:'◌'},{href:'/calendar',en:'Calendar',sv:'Kalender',icon:'⌁'},{href:'/water',en:'Water',sv:'Vatten',icon:'◍'},{href:'/nutrition',en:'Nutrition',sv:'Mat',icon:'◇'},{href:'/sleep',en:'Sleep',sv:'Sömn',icon:'◐'},{href:'/gym',en:'Gym',sv:'Gym',icon:'＋'},{href:'/individual',en:'Training',sv:'Träning',icon:'↗'},{href:'/theory',en:'Theory',sv:'Teori',icon:'▱'},{href:'/injury',en:'Recovery',sv:'Återhämtning',icon:'○'},{href:'/ai',en:'AI',sv:'AI',icon:'✦'},{href:'/progress',en:'Progress',sv:'Utveckling',icon:'↗'},{href:'/settings',en:'Settings',sv:'Inställningar',icon:'⚙'}
];
const mobileMain=[links[0],links[1],links[6],links[3],links[9]];
function Icon({icon}){return <span className="nav-icon" aria-hidden="true">{icon}</span>}
function PitchpathLogo({compact=false}){return <span className={`pitchpath-logo ${compact?'pitchpath-logo-compact':''}`} aria-label="Pitchpath"><svg viewBox="0 0 44 44" role="img" aria-hidden="true" style={{width:compact?32:34,height:compact?32:34,display:'block'}}><path d="M11.5 31V12.5h9.4c5.5 0 9 3 9 7.7s-3.5 7.7-9 7.7H17" fill="none" stroke="currentColor" strokeWidth="3.4" strokeLinecap="round" strokeLinejoin="round"/><path d="M17 22.7h14" fill="none" stroke="currentColor" strokeWidth="3.4" strokeLinecap="round"/><path d="M30.8 27.8c3 1.3 5.2 3.5 6.1 6" fill="none" stroke="currentColor" strokeWidth="2.4" strokeLinecap="round" opacity=".55"/><circle cx="37.2" cy="34.1" r="2.35" fill="currentColor"/></svg>{!compact&&<b>Pitchpath</b>}</span>}
export default function Nav(){const pathname=usePathname();const [lang,setLang]=useState('en');const [more,setMore]=useState(false);useEffect(()=>{const read=()=>setLang(localStorage.getItem('pitchpath-language')||'en');read();window.addEventListener('pitchpath-preferences',read);return()=>window.removeEventListener('pitchpath-preferences',read)},[]);if(pathname==='/login'||pathname==='/onboarding')return null;const activeIndex=Math.max(0,links.findIndex(l=>pathname===l.href||(l.href!=='/'&&pathname.startsWith(l.href))));const isMobileMain=mobileMain.some(l=>l.href===links[activeIndex]?.href);return <>
<div className="top-brand" aria-label="Pitchpath"><PitchpathLogo compact/><Link href="/settings" className="top-settings" aria-label={lang==='sv'?'Inställningar':'Settings'}>⚙</Link></div>
<aside className="side-nav" style={{maxHeight:'calc(100vh - 28px)',overflow:'hidden'}}><div className="brand-mark"><PitchpathLogo/></div><div className="side-nav-list" style={{gap:0}}><span className="nav-slider" style={{height:44,transform:`translateY(${activeIndex*44}px)`}} />{links.map((l,i)=><Link key={l.href} href={l.href} className={`side-nav-item ${i===activeIndex?'active':''}`} style={{height:44}}><Icon icon={l.icon}/><span>{lang==='sv'?l.sv:l.en}</span></Link>)}</div></aside>
<nav className="mobile-nav"><div className="mobile-nav-track"><div className="mobile-brand"><PitchpathLogo compact/></div>{mobileMain.map(l=>{const active=pathname===l.href||(l.href!=='/'&&pathname.startsWith(l.href));return <Link key={l.href} href={l.href} className={`mobile-nav-item ${active?'active':''}`}><Icon icon={l.icon}/><span>{lang==='sv'?l.sv:l.en}</span></Link>})}<button className={`mobile-nav-item mobile-more ${!isMobileMain?'active':''}`} onClick={()=>setMore(v=>!v)}><Icon icon="•••"/><span>{lang==='sv'?'Mer':'More'}</span></button></div></nav>
{more&&<div className="mobile-more-sheet" onClick={()=>setMore(false)}><div className="mobile-more-panel" onClick={e=>e.stopPropagation()}><div className="sheet-handle"/><div className="sheet-grid">{links.filter(l=>!mobileMain.includes(l)).map(l=><Link key={l.href} href={l.href} onClick={()=>setMore(false)} className="sheet-link"><Icon icon={l.icon}/><span>{lang==='sv'?l.sv:l.en}</span></Link>)}</div></div></div>}</>}
