'use client';
import { useEffect,useState } from 'react';
import { useRouter } from 'next/navigation';
import { supabase } from '../../lib/supabaseClient';
const copy={en:{title:'Settings',sub:'Control how Pitchpath works for you.',appearance:'Appearance',light:'Light',dark:'Dark',language:'Language',english:'English',swedish:'Svenska',football:'Football profile',team:'Team',division:'Division / competition',save:'Save changes',saved:'Saved',school:'School timing',start:'School starts',leave:'Leave home',buffer:'Wake before school',minutes:'minutes',updates:'Monthly player update',updatesSub:'Keep your profile current so your plans stay useful.',open:'Open monthly update',account:'Account'},sv:{title:'Inställningar',sub:'Bestäm hur Pitchpath ska fungera för dig.',appearance:'Utseende',light:'Ljust',dark:'Mörkt',language:'Språk',english:'English',swedish:'Svenska',football:'Fotbollsprofil',team:'Lag',division:'Division / tävling',save:'Spara ändringar',saved:'Sparat',school:'Skoltider',start:'Skolan börjar',leave:'Gå hemifrån',buffer:'Vakna före skolan',minutes:'minuter',updates:'Månadens spelaruppdatering',updatesSub:'Håll profilen aktuell så att planerna fortsätter vara relevanta.',open:'Öppna månadsuppdatering',account:'Konto'}};
export default function SettingsPage(){
 const router=useRouter();const [uid,setUid]=useState(null);const [form,setForm]=useState({team:'',division:'',school_start_time:'08:10',leave_home_time:'07:30',school_wake_buffer_minutes:60});const [language,setLanguage]=useState('en');const [theme,setTheme]=useState('light');const [saved,setSaved]=useState(false);const [message,setMessage]=useState('');const t=copy[language]||copy.en;
 useEffect(()=>{(async()=>{const {data}=await supabase.auth.getUser();if(!data.user){router.push('/login');return}setUid(data.user.id);const {data:p,error}=await supabase.from('profiles').select('*').eq('id',data.user.id).single();if(error){setMessage(error.message);return}if(p){setForm({team:p.team||'',division:p.division||p.league||'',school_start_time:(p.school_start_time||'08:10').slice(0,5),leave_home_time:(p.leave_home_time||'07:30').slice(0,5),school_wake_buffer_minutes:p.school_wake_buffer_minutes??60});setLanguage(p.language||localStorage.getItem('pitchpath-language')||'en');setTheme(p.theme||localStorage.getItem('pitchpath-theme')||'light')}})()},[router]);
 const setPref=(field,value)=>setForm(f=>({...f,[field]:value}));
 async function save(){if(!uid)return;setMessage('');const {error}=await supabase.from('profiles').update({...form,language,theme,league:form.division}).eq('id',uid);if(error){setMessage(error.message);return}localStorage.setItem('pitchpath-language',language);localStorage.setItem('pitchpath-theme',theme);document.documentElement.dataset.theme=theme;document.documentElement.lang=language;window.dispatchEvent(new Event('pitchpath-preferences'));setSaved(true);setTimeout(()=>setSaved(false),1800)}
 return <main className="app-shell" style={{maxWidth:900}}><div style={{marginBottom:24}}><span className="pill">Pitchpath</span><h1 className="page-title" style={{marginTop:10}}>{t.title}</h1><p className="page-subtitle">{t.sub}</p></div><section className="card"><span className="pill">{t.appearance}</span><h2 style={{fontSize:27,marginTop:9}}>{t.appearance}</h2><div className="segmented"><button className={theme==='light'?'selected':''} onClick={()=>setTheme('light')}>☀︎ {t.light}</button><button className={theme==='dark'?'selected':''} onClick={()=>setTheme('dark')}>◐ {t.dark}</button></div></section><section className="card"><span className="pill">{t.language}</span><h2 style={{fontSize:27,marginTop:9}}>{t.language}</h2><div className="segmented"><button className={language==='en'?'selected':''} onClick={()=>setLanguage('en')}>🇬🇧 {t.english}</button><button className={language==='sv'?'selected':''} onClick={()=>setLanguage('sv')}>🇸🇪 {t.swedish}</button></div></section><section className="card"><span className="pill">{t.football}</span><h2 style={{fontSize:27,marginTop:9}}>{t.football}</h2><label className="setting-label">{t.team}<input className="input-field" value={form.team} onChange={e=>setPref('team',e.target.value)} /></label><label className="setting-label">{t.division}<input className="input-field" value={form.division} onChange={e=>setPref('division',e.target.value)} /></label></section><section className="card"><span className="pill">{t.school}</span><h2 style={{fontSize:27,marginTop:9}}>{t.school}</h2><div className="premium-grid"><label className="setting-label">{t.start}<input className="input-field" type="time" value={form.school_start_time} onChange={e=>setPref('school_start_time',e.target.value)} /></label><label className="setting-label">{t.leave}<input className="input-field" type="time" value={form.leave_home_time} onChange={e=>setPref('leave_home_time',e.target.value)} /></label><label className="setting-label">{t.buffer}<input className="input-field" type="number" min="15" max="180" value={form.school_wake_buffer_minutes} onChange={e=>setPref('school_wake_buffer_minutes',Number(e.target.value))} /><small className="muted">{t.minutes}</small></label></div></section><section className="card"><span className="pill">{t.updates}</span><h2 style={{fontSize:27,marginTop:9}}>{t.updates}</h2><p className="muted">{t.updatesSub}</p><button className="btn-secondary" onClick={()=>router.push('/progress')}>{t.open} →</button></section>{message&&<p className="muted">{message}</p>}<button className="btn-primary" onClick={save}>{saved?'✓ '+t.saved:t.save}</button></main>}
