'use client';
import { useEffect,useState } from 'react';
import { supabase } from '../../lib/supabaseClient';
import { localDateKey, localDateTime } from '../../lib/dateUtils';

const weekdayNames=['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'];
const weekdayMap={sunday:0,monday:1,tuesday:2,wednesday:3,thursday:4,friday:5,saturday:6,söndag:0,måndag:1,tisdag:2,onsdag:3,torsdag:4,fredag:5,lördag:6};
function normalizeWeekday(value){if(typeof value==='number'&&value>=0&&value<=6)return value;const n=Number(value);if(Number.isFinite(n)&&n>=0&&n<=6)return n;return weekdayMap[String(value||'monday').toLowerCase()]??1;}
function nextWeekday(weekday){const day=normalizeWeekday(weekday);const now=new Date();const target=new Date(now);const delta=(day-now.getDay()+7)%7;target.setDate(target.getDate()+delta);target.setHours(12,0,0,0);return target;}
function localDateFromDate(d){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;}
function hasOverlap(start,end,events){return (events||[]).some(e=>{const a=new Date(e.starts_at).getTime(),b=new Date(e.ends_at||e.starts_at).getTime();return start.getTime()<b&&end.getTime()>a;});}
function timeToMinutes(value){const [h,m]=String(value||'17:00').split(':').map(Number);return (Number.isFinite(h)?h:17)*60+(Number.isFinite(m)?m:0);}
function minutesToTime(total){const safe=Math.max(0,Math.min(23*60+59,total));return `${String(Math.floor(safe/60)).padStart(2,'0')}:${String(safe%60).padStart(2,'0')}`;}

export default function AiPage(){
 const [messages,setMessages]=useState([]),[input,setInput]=useState(''),[context,setContext]=useState(null),[loadingContext,setLoadingContext]=useState(true),[sending,setSending]=useState(false),[language,setLanguage]=useState('en');
 useEffect(()=>{(async()=>{try{const {data:u,error:authError}=await supabase.auth.getUser();if(authError||!u.user){setMessages([{role:'ai',text:'Please log in first.'}]);return}const uid=u.user.id;const [{data:profile,error:pe},{data:events,error:ee},{data:injuries,error:ie},{data:logs,error:le}]=await Promise.all([supabase.from('profiles').select('*').eq('id',uid).single(),supabase.from('calendar_events').select('*').eq('user_id',uid).order('starts_at').limit(300),supabase.from('injuries').select('*').eq('user_id',uid).eq('status','active'),supabase.from('nutrition_logs').select('*').eq('user_id',uid).order('created_at',{ascending:false}).limit(14)]);if(pe||ee||ie||le)throw new Error(pe?.message||ee?.message||ie?.message||le?.message||'Could not load your Pitchpath context.');const lang=profile?.language||localStorage.getItem('pitchpath-language')||'en';setLanguage(lang);setContext({uid,profile,upcomingEvents:events||[],activeInjuries:injuries||[],recentNutrition:logs||[]});setMessages([{role:'ai',text:lang==='sv'?'Pitchpath är redo. Säg vad du vill ändra så kontrollerar jag kalendern, konflikter och din träningsplan innan jag gör ändringen.':'Pitchpath is ready. Tell me what you want changed and I will check your calendar, conflicts and training plan before changing anything.'}])}catch(e){setMessages([{role:'ai',text:e.message||'Could not load Pitchpath.'}])}finally{setLoadingContext(false)}})()},[]);
 async function refreshContext(){if(!context?.uid)return;const [{data:events,error:ee},{data:profile,error:pe}]=await Promise.all([supabase.from('calendar_events').select('*').eq('user_id',context.uid).order('starts_at').limit(300),supabase.from('profiles').select('*').eq('id',context.uid).single()]);if(ee||pe)throw new Error(ee?.message||pe?.message||'Could not refresh Pitchpath context.');setContext(c=>c?{...c,profile,upcomingEvents:events||[]}:c);return events||[];}
 async function rebalance(){if(!context?.uid)return;const [{data:allEvents,error:eventsError},{data:injuries,error:injuryError}]=await Promise.all([supabase.from('calendar_events').select('*').eq('user_id',context.uid).gte('starts_at',new Date().toISOString()).order('starts_at').limit(300),supabase.from('injuries').select('*').eq('user_id',context.uid).eq('status','active')]);if(eventsError||injuryError)throw new Error(eventsError?.message||injuryError?.message||'Could not read your schedule.');const fixed=(allEvents||[]).filter(e=>!e.notes?.startsWith('[AI PLAN]')&&!e.notes?.startsWith('[AI RECOVERY]'));const localized=fixed.map(e=>({...e,local_start:new Date(e.starts_at).toLocaleString('sv-SE',{dateStyle:'short',timeStyle:'short'}),local_end:e.ends_at?new Date(e.ends_at).toLocaleString('sv-SE',{dateStyle:'short',timeStyle:'short'}):null}));const res=await fetch('/api/plan-training',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({profile:context.profile,events:localized,injuries:injuries||[],language:context.profile?.language||'en'})});const out=await res.json();if(!res.ok)throw new Error(out?.error||'Could not rebalance training.');const rows=(out.sessions||[]).filter(s=>s.day&&s.start_time&&s.type).map(s=>{const start=localDateTime(s.day,s.start_time);const end=s.end_time?localDateTime(s.day,s.end_time):null;return {user_id:context.uid,type:s.type,title:`${s.title||'Pitchpath session'} · AI`,starts_at:start.toISOString(),ends_at:end?end.toISOString():null,notes:`[AI PLAN] ${s.description||''}`};});const oldIds=(allEvents||[]).filter(e=>e.notes?.startsWith('[AI PLAN]')||e.notes?.startsWith('[AI RECOVERY]')).map(e=>e.id);if(oldIds.length){const {error}=await supabase.from('calendar_events').delete().in('id',oldIds);if(error)throw error;}if(rows.length){const {error}=await supabase.from('calendar_events').insert(rows);if(error)throw error;}await refreshContext();return rows.length;}
 function requestedTime(action,date,currentEvents){let startTime=action.start_time||'17:00';if(action.after_school){const daySchool=(currentEvents||[]).filter(e=>e.type==='school'&&localDateFromDate(new Date(e.starts_at))===localDateFromDate(date));if(daySchool.length){const latest=daySchool.reduce((latest,e)=>{const end=new Date(e.ends_at||e.starts_at);return end>latest?end:latest},new Date(0));startTime=minutesToTime(latest.getHours()*60+latest.getMinutes()+30);}else if(context?.profile?.school_start_time){startTime=action.start_time||'17:00';}}return startTime;}
 async function addRecurring(action){const weeks=Math.min(Math.max(Number(action.weeks)||8,1),16);const weekday=normalizeWeekday(action.weekday);const base=nextWeekday(weekday);const duration=Math.min(Math.max(Number(action.duration_minutes)||60,20),180);const currentEvents=context.upcomingEvents||[];const rows=[];const conflicts=[];for(let i=0;i<weeks;i++){const startDate=new Date(base);startDate.setDate(base.getDate()+i*7);const dateKey=localDateFromDate(startDate);const startTime=requestedTime(action,startDate,currentEvents);const start=localDateTime(dateKey,startTime);const end=new Date(start.getTime()+duration*60000);if(hasOverlap(start,end,currentEvents)||hasOverlap(start,end,rows)){conflicts.push(`${weekdayNames[weekday]} ${dateKey} ${startTime}`);continue;}rows.push({user_id:context.uid,type:action.event_type||'gym',title:action.title||'Gym',starts_at:start.toISOString(),ends_at:end.toISOString(),notes:`[PLAYER RECURRING] weekly · ${action.notes||''}`});}
 if(!rows.length)throw new Error(`Every requested ${weekdayNames[weekday]} session conflicts with your existing calendar.`);
 const {error}=await supabase.from('calendar_events').insert(rows);if(error)throw error;await refreshContext();let rebuilt=0;try{rebuilt=await rebalance();}catch(e){throw new Error(`The recurring sessions were saved, but the training plan could not be rebuilt: ${e.message}`)}const skipped=conflicts.length?` ${conflicts.length} conflicting week${conflicts.length===1?' was':'s were'} skipped.`:'';return language==='sv'?`Jag lade in ${action.title||'gym'} varje ${weekdayNames[weekday]} i ${rows.length} veckor.${skipped} Träningsplanen justerades${rebuilt?' och kalendern uppdaterades.':'.'}`:`I added ${action.title||'gym'} every ${weekdayNames[weekday]} for ${rows.length} weeks.${skipped} The training plan was rebuilt and the calendar updated.`;}
 async function removeRecurring(action){const weekday=action.weekday==null?null:normalizeWeekday(action.weekday);const future=new Date().toISOString();let candidates=(context.upcomingEvents||[]).filter(e=>e.notes?.startsWith('[PLAYER RECURRING]')&&new Date(e.starts_at)>=new Date(future));if(action.title)candidates=candidates.filter(e=>e.title.toLowerCase().includes(String(action.title).toLowerCase()));if(weekday!=null)candidates=candidates.filter(e=>new Date(e.starts_at).getDay()===weekday);const ids=candidates.map(e=>e.id);if(!ids.length)return language==='sv'?'Jag hittade ingen matchande återkommande aktivitet.':'I could not find a matching recurring activity.';const {error}=await supabase.from('calendar_events').delete().in('id',ids);if(error)throw error;await refreshContext();await rebalance();return language==='sv'?'Den återkommande aktiviteten är borttagen och planen är ombyggd.':'The recurring activity was removed and the plan was rebuilt.';}
 async function replaceRecurring(action){await removeRecurring({title:action.old_title||'Gym',weekday:action.old_weekday});return addRecurring(action);}
 async function apply(action){if(!action||!context?.uid)return null;if(action.type==='add_recurring_event')return addRecurring(action);if(action.type==='remove_recurring_event')return removeRecurring(action);if(action.type==='replace_recurring_event')return replaceRecurring(action);if(action.type==='update_weaknesses'){const {error}=await supabase.from('profiles').update({weaknesses:action.weaknesses}).eq('id',context.uid);if(error)throw error;setContext(c=>c?{...c,profile:{...c.profile,weaknesses:action.weaknesses}}:c);await rebalance();return language==='sv'?'Svagheter uppdaterade och träningsplanen justerad.':'Weaknesses updated and the training plan was adjusted.';}if(action.type==='update_profile'){const fields=action.fields||{};const {error}=await supabase.from('profiles').update(fields).eq('id',context.uid);if(error)throw error;setContext(c=>c?{...c,profile:{...c.profile,...fields}}:c);if(['team','division','school_start_time','leave_home_time'].some(k=>k in fields))await rebalance();return language==='sv'?'Profilen är uppdaterad.':'Profile updated.';}if(action.type==='add_calendar_event'){const weekday=normalizeWeekday(action.weekday);const target=nextWeekday(weekday);const dateKey=localDateFromDate(target);const startTime=requestedTime(action,target,context.upcomingEvents||[]);const start=localDateTime(dateKey,startTime);const end=new Date(start.getTime()+(Math.min(Math.max(Number(action.duration_minutes)||60,15),240))*60000);if(hasOverlap(start,end,context.upcomingEvents||[]))throw new Error('That time conflicts with an existing calendar event.');const {error}=await supabase.from('calendar_events').insert({user_id:context.uid,type:action.event_type||'personal',title:action.title||'Personal',starts_at:start.toISOString(),ends_at:end.toISOString(),notes:action.notes||'[AI ASSISTANT] Added at player request'});if(error)throw error;await refreshContext();await rebalance();return language==='sv'?`La till ${action.title||'aktiviteten'} och justerade planen.`:`Added ${action.title||'event'} and rebalanced the plan.`;}if(action.type==='rebuild_training'){const count=await rebalance();return language==='sv'?`Träningskalendern är omplanerad${count?` med ${count} pass`:''}.`:`Training calendar rebuilt${count?` with ${count} sessions`:''}.`;}if(action.type==='log_note')return language==='sv'?'Antecknat.':'Noted.';return null;}
 async function send(){if(!input.trim()||sending||loadingContext||!context)return;const msg=input.trim();setInput('');setMessages(m=>[...m,{role:'user',text:msg}]);setSending(true);try{const res=await fetch('/api/assistant',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:msg,context})});const out=await res.json();let suffix='';if(out.action){try{const result=await apply(out.action);suffix=result?` ${result}`:'';}catch(e){suffix=` ${language==='sv'?`Ändringen misslyckades: ${e.message}`:`I couldn't apply that change: ${e.message}`}`;}}setMessages(m=>[...m,{role:'ai',text:(out.reply||'I could not determine an action.')+suffix}]);}catch(e){setMessages(m=>[...m,{role:'ai',text:e.message||'Something went wrong. Please try again.'}]);}finally{setSending(false);}}
 return <main className="app-shell"><div style={{marginBottom:22}}><span className="pill">Pitchpath AI</span><h1 className="page-title" style={{marginTop:10}}>{language==='sv'?'Ditt prestationssystem.':'Your performance brain.'}</h1><p className="page-subtitle">{language==='sv'?'Be mig ändra kalendern, träningsbelastningen eller din profil. Jag kontrollerar konflikter innan jag gör ändringar.':'Tell me what you want to change. I check your full week, school, football, recovery and conflicts before changing anything.'}</p></div><section className="card" style={{minHeight:520,display:'flex',flexDirection:'column'}}><div style={{flex:1,display:'flex',flexDirection:'column',gap:12}}>{messages.map((m,i)=><div key={i} className="premium-tile" style={{alignSelf:m.role==='user'?'flex-end':'flex-start',maxWidth:'82%',background:m.role==='user'?'var(--pine)':'rgba(255,252,249,.7)',color:m.role==='user'?'#fff':'var(--ink)'}}>{m.text}</div>)}{(sending||loadingContext)&&<div className="muted">{language==='sv'?'Tänker…':'Thinking…'}</div>}</div><div style={{display:'flex',gap:9,marginTop:18}}><input className="input-field" disabled={loadingContext||sending||!context} value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>e.key==='Enter'&&send()} placeholder={language==='sv'?'T.ex. Jag vill gymma varje måndag efter skolan':'e.g. I want gym every Monday after school'}/><button className="btn-primary" onClick={send} disabled={loadingContext||sending||!context}>{language==='sv'?'Skicka':'Send'}</button></div></section></main>}
