'use client';
import { useEffect,useState } from 'react';
import { supabase } from '../../lib/supabaseClient';
import { localDateKey } from '../../lib/dateUtils';
export default function GymPage(){
 const [uid,setUid]=useState(null),[profile,setProfile]=useState(null),[session,setSession]=useState(null),[loading,setLoading]=useState(false),[message,setMessage]=useState('');
 useEffect(()=>{(async()=>{const {data:{user}}=await supabase.auth.getUser();if(!user){setMessage('Please log in to use the gym planner.');return}setUid(user.id);const [{data:p,error:pe},{data:s,error:se}]=await Promise.all([supabase.from('profiles').select('*').eq('id',user.id).maybeSingle(),supabase.from('gym_sessions').select('*').eq('user_id',user.id).eq('scheduled_for',localDateKey()).maybeSingle()]);if(pe||se)setMessage(pe?.message||se?.message||'Could not load the gym planner.');setProfile(p||{});setSession(s||null)})()},[]);
 async function generate(){if(!uid)return;setLoading(true);setMessage('');try{const [{data:events,error:ee},{data:injuries,error:ie}]=await Promise.all([supabase.from('calendar_events').select('*').eq('user_id',uid).gte('starts_at',new Date().toISOString()).order('starts_at').limit(14),supabase.from('injuries').select('*').eq('user_id',uid).eq('status','active')]);if(ee||ie)throw new Error(ee?.message||ie?.message||'Could not read your schedule.');const res=await fetch('/api/generate-gym',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({profile,events:events||[],injuries:injuries||[]})});const out=await res.json();if(!res.ok)throw new Error(out?.error||'The gym coach could not generate a session.');if(!out.exercises?.length)throw new Error('No gym session was recommended for today. Your calendar or recovery status may call for recovery.');const exercises=out.exercises.map(x=>({...x,completed:false}));const today=localDateKey();const {data:saved,error}=await supabase.from('gym_sessions').upsert({user_id:uid,scheduled_for:today,exercises,summary:out.summary},{onConflict:'user_id,scheduled_for'}).select().single();if(error)throw error;setSession(saved)}catch(e){setMessage(e.message||'Could not build the gym session.')}finally{setLoading(false)}}
 async function toggle(i){if(!session)return;const updated=session.exercises.map((x,n)=>n===i?{...x,completed:!x.completed}:x);setSession({...session,exercises:updated});const {error}=await supabase.from('gym_sessions').update({exercises:updated,updated_at:new Date().toISOString()}).eq('id',session.id);if(error)setMessage(error.message)}
 const done=session?.exercises?.filter(x=>x.completed).length||0,total=session?.exercises?.length||0;
 return <main className="app-shell"><div style={{marginBottom:22}}><span className="pill">Strength & power</span><h1 className="page-title" style={{marginTop:10}}>Gym, built for football.</h1><p className="page-subtitle">A schedule-aware session shaped by position, goals, training load and recovery — not a generic split.</p></div><section className="card" style={{background:'linear-gradient(135deg,#202522,#3D4941)',color:'#fff'}}><div style={{display:'flex',justifyContent:'space-between',gap:18,alignItems:'center',flexWrap:'wrap'}}><div><span style={{fontSize:11,opacity:.6,fontWeight:800}}>TODAY</span><h2 style={{fontSize:31,marginTop:6}}>{session?'Session ready.':'Ready when you are.'}</h2><p style={{opacity:.72,maxWidth:600,marginBottom:0}}>{session?.summary||'Build a session from your real calendar, recovery and player profile.'}</p></div><button className="btn-secondary" style={{background:'rgba(255,255,255,.1)',color:'#fff',borderColor:'rgba(255,255,255,.18)'}} onClick={generate} disabled={loading}>{loading?'Building…':session?'Rebuild session':'Build today'}</button></div></section>{session&&<section className="card"><div style={{display:'flex',justifyContent:'space-between',alignItems:'end'}}><div><span className="pill">Progress</span><div className="metric" style={{marginTop:5}}>{done}/{total}</div><div className="muted">exercises completed</div></div><div style={{width:180}}><div className="progress-track"><div className="progress-fill" style={{width:`${total?done/total*100:0}%`}}/></div></div></div><div style={{marginTop:18}}>{session.exercises.map((x,i)=><button key={i} onClick={()=>toggle(i)} className="premium-tile" style={{display:'flex',width:'100%',textAlign:'left',alignItems:'center',gap:14,marginBottom:9,border:0,opacity:x.completed?.72:1}}><span style={{width:34,height:34,borderRadius:'50%',display:'grid',placeItems:'center',background:x.completed?'var(--pine)':'rgba(131,151,136,.1)',color:x.completed?'#fff':'var(--ink)',fontWeight:800}}>{x.completed?'✓':i+1}</span><span style={{flex:1}}><strong>{x.name}</strong><br/><small className="muted">{x.sets} sets × {x.reps} · {x.rest_seconds}s rest</small><br/><small className="muted">{x.purpose}</small></span></button>)}</div></section>}{message&&<div className="card" style={{borderColor:'rgba(169,74,66,.25)'}}><strong>Gym update</strong><p className="muted" style={{marginBottom:0}}>{message}</p></div>}</main>}
